import type { School } from '@/types';

export type SeedSchool = Omit<School, 'id' | 'created_at'>;

export const seedSchools: SeedSchool[] = [
  // ====== 美国 (28) ======
  {
    name: '麻省理工学院',
    name_en: 'Massachusetts Institute of Technology',
    country: '美国',
    ranking: 1,
    website: 'https://www.mit.edu',
    description:
      '麻省理工学院是全球顶尖的理工科大学，以工程、计算机科学和自然科学闻名于世。MIT培养了众多诺贝尔奖得主和科技企业家，校园位于马萨诸塞州剑桥市，毗邻波士顿，拥有世界一流的实验室和创新生态系统。',
    requirements: { gpa_min: '3.8/4.0', toefl_min: 100, ielts_min: 7.5, gre: '建议325+' },
    tuition: '约$60,000/年',
    application_deadline: '12月15日（早申）/ 1月5日（常规）',
    logo_url: null,
  },
  {
    name: '哈佛大学',
    name_en: 'Harvard University',
    country: '美国',
    ranking: 4,
    website: 'https://www.harvard.edu',
    description:
      '哈佛大学是美国历史最悠久的高等学府，在商学、法学、医学、人文社科等领域均居世界领先地位。位于马萨诸塞州剑桥市，拥有全球最大的大学图书馆系统和庞大的校友网络。',
    requirements: { gpa_min: '3.8/4.0', toefl_min: 100, ielts_min: 7.5, gre: '建议325+' },
    tuition: '约$59,000/年',
    application_deadline: '12月1日（早申）/ 1月1日（常规）',
    logo_url: null,
  },
  {
    name: '斯坦福大学',
    name_en: 'Stanford University',
    country: '美国',
    ranking: 6,
    website: 'https://www.stanford.edu',
    description:
      '斯坦福大学位于硅谷核心地带，以其创新创业精神和顶尖的工程、商学教育闻名。培养了Google、HP等众多科技巨头的创始人，校园占地8,180英亩，环境优美。',
    requirements: { gpa_min: '3.8/4.0', toefl_min: 100, ielts_min: 7.5, gre: '建议325+' },
    tuition: '约$62,000/年',
    application_deadline: '11月1日（早申）/ 12月15日（常规）',
    logo_url: null,
  },
  {
    name: '加州理工学院',
    name_en: 'California Institute of Technology',
    country: '美国',
    ranking: 10,
    website: 'https://www.caltech.edu',
    description:
      '加州理工学院是一所规模虽小但极其精英的理工科大学，在物理、天文、工程和计算机科学领域享有盛誉。师生比极低，科研强度极高，管理着NASA喷气推进实验室。',
    requirements: { gpa_min: '3.8/4.0', toefl_min: 100, ielts_min: 7.5, gre: '建议330+' },
    tuition: '约$63,000/年',
    application_deadline: '12月1日（早申）/ 1月3日（常规）',
    logo_url: null,
  },
  {
    name: '普林斯顿大学',
    name_en: 'Princeton University',
    country: '美国',
    ranking: 14,
    website: 'https://www.princeton.edu',
    description:
      '普林斯顿大学是常春藤盟校之一，以数学、物理、经济学和公共事务等学科著称。校园建筑为哥特式风格，学术氛围浓厚，本科教育质量稳居全美第一。',
    requirements: { gpa_min: '3.8/4.0', toefl_min: 100, ielts_min: 7.5, gre: '建议325+' },
    tuition: '约$58,000/年',
    application_deadline: '11月1日（早申）/ 1月1日（常规）',
    logo_url: null,
  },
  {
    name: '耶鲁大学',
    name_en: 'Yale University',
    country: '美国',
    ranking: 15,
    website: 'https://www.yale.edu',
    description:
      '耶鲁大学是常春藤盟校之一，以法学、艺术、人文和生命科学见长。位于康涅狄格州纽黑文，拥有丰富的博物馆和图书馆资源，法学院长期排名全美第一。',
    requirements: { gpa_min: '3.7/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议325+' },
    tuition: '约$60,000/年',
    application_deadline: '11月1日（早申）/ 1月2日（常规）',
    logo_url: null,
  },
  {
    name: '哥伦比亚大学',
    name_en: 'Columbia University',
    country: '美国',
    ranking: 18,
    website: 'https://www.columbia.edu',
    description:
      '哥伦比亚大学位于纽约曼哈顿，是常春藤盟校之一，在新闻学、商学、国际关系和法学领域具有突出优势。得益于纽约的区位优势，实习和就业机会极为丰富。',
    requirements: { gpa_min: '3.7/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约$65,000/年',
    application_deadline: '11月15日（早申）/ 1月1日（常规）',
    logo_url: null,
  },
  {
    name: '宾夕法尼亚大学',
    name_en: 'University of Pennsylvania',
    country: '美国',
    ranking: 11,
    website: 'https://www.upenn.edu',
    description:
      '宾夕法尼亚大学是常春藤盟校，沃顿商学院全球排名第一，在金融、管理和创业教育方面享有盛名。学校强调跨学科教育，位于费城，校园融合了历史与现代风格。',
    requirements: { gpa_min: '3.7/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议325+' },
    tuition: '约$63,000/年',
    application_deadline: '11月1日（早申）/ 1月5日（常规）',
    logo_url: null,
  },
  {
    name: '康奈尔大学',
    name_en: 'Cornell University',
    country: '美国',
    ranking: 24,
    website: 'https://www.cornell.edu',
    description:
      '康奈尔大学是常春藤盟校中规模最大的大学，在工程、农学、酒店管理和计算机科学等领域实力雄厚。位于纽约州伊萨卡，校园风景如画，兼具公立和私立办学特色。',
    requirements: { gpa_min: '3.6/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约$62,000/年',
    application_deadline: '11月1日（早申）/ 1月2日（常规）',
    logo_url: null,
  },
  {
    name: '杜克大学',
    name_en: 'Duke University',
    country: '美国',
    ranking: 29,
    website: 'https://www.duke.edu',
    description:
      '杜克大学素有"南方哈佛"之称，在医学、商学、公共政策和工程学方面表现突出。位于北卡罗来纳州，校园以哥特式建筑和杜克教堂闻名，篮球队更是全美顶尖。',
    requirements: { gpa_min: '3.6/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约$63,000/年',
    application_deadline: '11月1日（早申）/ 1月2日（常规）',
    logo_url: null,
  },
  {
    name: '约翰霍普金斯大学',
    name_en: 'Johns Hopkins University',
    country: '美国',
    ranking: 23,
    website: 'https://www.jhu.edu',
    description:
      '约翰霍普金斯大学以医学、公共卫生、生物医学工程和国际关系享誉全球。医学院和公共卫生学院长期排名全美第一，也是美国第一所研究型大学。',
    requirements: { gpa_min: '3.6/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约$60,000/年',
    application_deadline: '11月1日（早申）/ 1月3日（常规）',
    logo_url: null,
  },
  {
    name: '加州大学伯克利分校',
    name_en: 'University of California, Berkeley',
    country: '美国',
    ranking: 12,
    website: 'https://www.berkeley.edu',
    description:
      'UC Berkeley是全球最好的公立大学之一，在计算机科学、工程、经济学和化学等领域位居世界前列。位于旧金山湾区，是自由思想和科技创新的摇篮，毗邻硅谷。',
    requirements: { gpa_min: '3.5/4.0', toefl_min: 90, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约$44,000/年（州外）',
    application_deadline: '12月1日（多数项目）',
    logo_url: null,
  },
  {
    name: '加州大学洛杉矶分校',
    name_en: 'University of California, Los Angeles',
    country: '美国',
    ranking: 27,
    website: 'https://www.ucla.edu',
    description:
      'UCLA是西海岸最受欢迎的公立大学之一，在影视艺术、医学、工程和商学等领域表现出色。位于洛杉矶西部，气候宜人，校园文化多元，体育传统悠久。',
    requirements: { gpa_min: '3.5/4.0', toefl_min: 87, ielts_min: 7.0, gre: '建议315+' },
    tuition: '约$43,000/年（州外）',
    application_deadline: '12月1日（多数项目）',
    logo_url: null,
  },
  {
    name: '卡内基梅隆大学',
    name_en: 'Carnegie Mellon University',
    country: '美国',
    ranking: 22,
    website: 'https://www.cmu.edu',
    description:
      '卡内基梅隆大学是全球计算机科学和人工智能领域的最顶尖学府之一，戏剧、设计和商学也享有盛誉。位于匹兹堡，以跨学科研究和实践导向教育著称。',
    requirements: { gpa_min: '3.5/4.0', toefl_min: 100, ielts_min: 7.5, gre: '建议325+' },
    tuition: '约$61,000/年',
    application_deadline: '12月1日（早申）/ 1月15日（常规）',
    logo_url: null,
  },
  {
    name: '纽约大学',
    name_en: 'New York University',
    country: '美国',
    ranking: 34,
    website: 'https://www.nyu.edu',
    description:
      '纽约大学是一所全球化综合大学，以商学（Stern）、法学、艺术（Tisch）和公共事务闻名。主校区位于纽约曼哈顿格林威治村，同时在阿布扎比和上海设有分校。',
    requirements: { gpa_min: '3.5/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约$58,000/年',
    application_deadline: '11月1日（早申）/ 1月5日（常规）',
    logo_url: null,
  },
  {
    name: '密歇根大学安娜堡分校',
    name_en: 'University of Michigan, Ann Arbor',
    country: '美国',
    ranking: 30,
    website: 'https://www.umich.edu',
    description:
      '密歇根大学安娜堡分校是美国顶尖公立研究型大学，在工程、商学、法学和社会科学等领域全面发展。校园体育氛围浓厚，"Go Blue"精神深入每位学生心中。',
    requirements: { gpa_min: '3.4/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议318+' },
    tuition: '约$53,000/年（州外）',
    application_deadline: '12月1日（早申）/ 2月1日（常规）',
    logo_url: null,
  },
  {
    name: '伊利诺伊大学香槟分校',
    name_en: 'University of Illinois Urbana-Champaign',
    country: '美国',
    ranking: 37,
    website: 'https://www.illinois.edu',
    description:
      'UIUC在计算机科学和工程领域排名极高，尤其是CS专业常年稳居全美前五。位于伊利诺伊州双子城，学费在同类学校中较为亲民，性价比极高。',
    requirements: { gpa_min: '3.4/4.0', toefl_min: 100, ielts_min: 6.5, gre: '建议315+' },
    tuition: '约$35,000/年（州外）',
    application_deadline: '12月15日（优先）/ 滚动录取',
    logo_url: null,
  },
  {
    name: '佐治亚理工学院',
    name_en: 'Georgia Institute of Technology',
    country: '美国',
    ranking: 38,
    website: 'https://www.gatech.edu',
    description:
      'Georgia Tech以工程和计算机科学闻名世界，工业工程、航空航天等专业常年排名前列。位于亚特兰大市中心，学费性价比高，毕业生就业率极高。',
    requirements: { gpa_min: '3.4/4.0', toefl_min: 90, ielts_min: 7.0, gre: '建议318+' },
    tuition: '约$31,000/年（州外）',
    application_deadline: '10月15日（早申）/ 12月15日（常规）',
    logo_url: null,
  },
  {
    name: '德克萨斯大学奥斯汀分校',
    name_en: 'University of Texas at Austin',
    country: '美国',
    ranking: 41,
    website: 'https://www.utexas.edu',
    description:
      'UT Austin是德克萨斯州旗舰大学，在计算机科学、工程、商学和石油工程领域实力强劲。位于"硅山"奥斯汀，科技公司云集，就业前景广阔。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 79, ielts_min: 6.5, gre: '建议315+' },
    tuition: '约$40,000/年（州外）',
    application_deadline: '12月1日（优先）/ 滚动录取',
    logo_url: null,
  },
  {
    name: '南加州大学',
    name_en: 'University of Southern California',
    country: '美国',
    ranking: 47,
    website: 'https://www.usc.edu',
    description:
      'USC是洛杉矶最富盛名的私立大学之一，在电影艺术、传媒、工程和商学领域享有国际声誉。校园文化活跃，校友网络庞大，国际学生比例高。',
    requirements: { gpa_min: '3.5/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议318+' },
    tuition: '约$64,000/年',
    application_deadline: '12月1日（早申）/ 1月15日（常规）',
    logo_url: null,
  },
  {
    name: '华盛顿大学西雅图分校',
    name_en: 'University of Washington, Seattle',
    country: '美国',
    ranking: 39,
    website: 'https://www.washington.edu',
    description:
      '华盛顿大学在计算机科学、医学和海洋科学等领域全球领先，是微软、亚马逊等科技巨头的重要人才基地。校园樱花季美不胜收，西雅图生活质量高。',
    requirements: { gpa_min: '3.4/4.0', toefl_min: 92, ielts_min: 7.0, gre: '建议315+' },
    tuition: '约$40,000/年（州外）',
    application_deadline: '12月15日（多数项目）',
    logo_url: null,
  },
  {
    name: '西北大学',
    name_en: 'Northwestern University',
    country: '美国',
    ranking: 32,
    website: 'https://www.northwestern.edu',
    description:
      '西北大学是一所位于芝加哥郊区的顶尖私立研究型大学，以商学（Kellogg）、新闻学（Medill）和传播学著称。校园沿密歇根湖而建，风景优美。',
    requirements: { gpa_min: '3.6/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议322+' },
    tuition: '约$63,000/年',
    application_deadline: '11月1日（早申）/ 1月2日（常规）',
    logo_url: null,
  },
  {
    name: '芝加哥大学',
    name_en: 'University of Chicago',
    country: '美国',
    ranking: 26,
    website: 'https://www.uchicago.edu',
    description:
      '芝加哥大学以经济学、社会学、法学和物理学领域的"芝加哥学派"闻名，经济学尤为突出。校园位于芝加哥海德公园，学术氛围极其严谨，崇尚批判性思维。',
    requirements: { gpa_min: '3.7/4.0', toefl_min: 104, ielts_min: 7.0, gre: '建议325+' },
    tuition: '约$64,000/年',
    application_deadline: '11月1日（早申）/ 1月3日（常规）',
    logo_url: null,
  },
  {
    name: '布朗大学',
    name_en: 'Brown University',
    country: '美国',
    ranking: 40,
    website: 'https://www.brown.edu',
    description:
      '布朗大学是常春藤盟校，以开放课程体系闻名，学生可自由设计学习计划，无必修通识课程。在计算机科学、生命科学和人文学科领域具有独特优势。',
    requirements: { gpa_min: '3.7/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约$63,000/年',
    application_deadline: '11月1日（早申）/ 1月5日（常规）',
    logo_url: null,
  },
  {
    name: '达特茅斯学院',
    name_en: 'Dartmouth College',
    country: '美国',
    ranking: 46,
    website: 'https://www.dartmouth.edu',
    description:
      '达特茅斯学院是常春藤盟校中规模最小、最重视本科教育的大学，以商学（Tuck）和文理教育著称。位于新罕布什尔州，校园文化和户外活动丰富。',
    requirements: { gpa_min: '3.7/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约$62,000/年',
    application_deadline: '11月1日（早申）/ 1月2日（常规）',
    logo_url: null,
  },
  {
    name: '普渡大学西拉法叶分校',
    name_en: 'Purdue University, West Lafayette',
    country: '美国',
    ranking: 49,
    website: 'https://www.purdue.edu',
    description:
      '普渡大学以工程学科闻名全美，航空航天、机械工程和计算机科学尤为突出，培养了众多NASA宇航员。学费多年未涨，是性价比最高的公立大学之一。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 80, ielts_min: 6.5, gre: '建议312+' },
    tuition: '约$31,000/年（州外）',
    application_deadline: '11月1日（早申）/ 1月15日（常规）',
    logo_url: null,
  },
  {
    name: '波士顿大学',
    name_en: 'Boston University',
    country: '美国',
    ranking: 52,
    website: 'https://www.bu.edu',
    description:
      '波士顿大学位于波士顿市中心，是一所大型私立研究型大学，在传播学、生物医学、法学和商学领域优势明显。国际学生群体庞大，校园与城市融为一体。',
    requirements: { gpa_min: '3.4/4.0', toefl_min: 90, ielts_min: 7.0, gre: '建议312+' },
    tuition: '约$62,000/年',
    application_deadline: '11月1日（早申）/ 1月4日（常规）',
    logo_url: null,
  },

  // ====== 英国 (10) ======
  {
    name: '牛津大学',
    name_en: 'University of Oxford',
    country: '英国',
    ranking: 3,
    website: 'https://www.ox.ac.uk',
    description:
      '牛津大学是英语世界最古老的大学，在人文、社会科学、医学和自然科学各领域均居世界前列。拥有独特的学院制和导师制，培养了众多英国首相和诺贝尔奖得主。',
    requirements: { gpa_min: '3.7/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约£35,000/年（国际生）',
    application_deadline: '1月7日（牛津/剑桥早申）',
    logo_url: null,
  },
  {
    name: '剑桥大学',
    name_en: 'University of Cambridge',
    country: '英国',
    ranking: 5,
    website: 'https://www.cam.ac.uk',
    description:
      '剑桥大学与牛津齐名，在自然科学、工程、数学和经济学领域具有世界级声誉。学院制历史悠久，培养了牛顿、达尔文等众多科学巨匠，科研实力雄厚。',
    requirements: { gpa_min: '3.7/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约£35,000/年（国际生）',
    application_deadline: '1月7日（牛津/剑桥早申）',
    logo_url: null,
  },
  {
    name: '帝国理工学院',
    name_en: 'Imperial College London',
    country: '英国',
    ranking: 2,
    website: 'https://www.imperial.ac.uk',
    description:
      '帝国理工学院是世界顶级的理工医学类大学，在工程、计算机、医学和商学领域位居全球前列。位于伦敦南肯辛顿，与众多科技和金融机构紧密合作。',
    requirements: { gpa_min: '3.5/4.0', toefl_min: 92, ielts_min: 6.5, gre: '建议318+' },
    tuition: '约£38,000/年（国际生）',
    application_deadline: '1月30日（多数项目）',
    logo_url: null,
  },
  {
    name: '伦敦大学学院',
    name_en: 'University College London',
    country: '英国',
    ranking: 9,
    website: 'https://www.ucl.ac.uk',
    description:
      'UCL是伦敦第一所大学，在建筑、教育、考古、医学和计算机科学等领域排名全球顶尖。位于伦敦市中心，是英国规模最大、学科最全的大学之一。',
    requirements: { gpa_min: '3.4/4.0', toefl_min: 92, ielts_min: 6.5, gre: '建议315+' },
    tuition: '约£32,000/年（国际生）',
    application_deadline: '3月31日（多数项目）/ 滚动录取',
    logo_url: null,
  },
  {
    name: '爱丁堡大学',
    name_en: 'University of Edinburgh',
    country: '英国',
    ranking: 21,
    website: 'https://www.ed.ac.uk',
    description:
      '爱丁堡大学是苏格兰最古老的大学之一，在人工智能、医学、文学和地球科学领域享有盛誉。位于爱丁堡古城，每年举办世界最大的艺术节，文化氛围浓厚。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 92, ielts_min: 6.5, gre: '建议310+' },
    tuition: '约£28,000/年（国际生）',
    application_deadline: '6月30日（多数项目）/ 滚动录取',
    logo_url: null,
  },
  {
    name: '曼彻斯特大学',
    name_en: 'University of Manchester',
    country: '英国',
    ranking: 28,
    website: 'https://www.manchester.ac.uk',
    description:
      '曼彻斯特大学是英国最大的单一校址大学，在材料科学、化学、工程和商学领域表现突出。石墨烯的发现就诞生于此，校园位于英国著名的工业和文化城市曼彻斯特。',
    requirements: { gpa_min: '3.2/4.0', toefl_min: 90, ielts_min: 6.5, gre: '建议310+' },
    tuition: '约£27,000/年（国际生）',
    application_deadline: '滚动录取（建议6月前）',
    logo_url: null,
  },
  {
    name: '伦敦国王学院',
    name_en: "King's College London",
    country: '英国',
    ranking: 31,
    website: 'https://www.kcl.ac.uk',
    description:
      'KCL是伦敦大学的创始学院之一，在法学、医学、国际关系和人文社科领域实力雄厚。位于伦敦泰晤士河畔，地理位置优越，与政界和法律界联系紧密。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 92, ielts_min: 6.5, gre: '建议312+' },
    tuition: '约£30,000/年（国际生）',
    application_deadline: '3月31日（多数项目）/ 滚动录取',
    logo_url: null,
  },
  {
    name: '华威大学',
    name_en: 'University of Warwick',
    country: '英国',
    ranking: 44,
    website: 'https://www.warwick.ac.uk',
    description:
      '华威大学是英国顶尖的研究型大学，以商学（WBS）、经济学和数学闻名。位于英格兰考文垂郊区，虽然建校时间较短，但已迅速跻身世界一流大学行列。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 92, ielts_min: 6.5, gre: '建议312+' },
    tuition: '约£28,000/年（国际生）',
    application_deadline: '7月31日（多数项目）/ 滚动录取',
    logo_url: null,
  },
  {
    name: '伦敦政治经济学院',
    name_en: 'London School of Economics and Political Science',
    country: '英国',
    ranking: 42,
    website: 'https://www.lse.ac.uk',
    description:
      'LSE是全球社会科学领域最顶尖的大学之一，经济学、政治学、社会学和法学均位列世界前三。位于伦敦市中心，毕业生在金融、咨询和政府领域就业优势明显。',
    requirements: { gpa_min: '3.6/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约£27,000/年（国际生）',
    application_deadline: '滚动录取（建议1月前）',
    logo_url: null,
  },
  {
    name: '布里斯托大学',
    name_en: 'University of Bristol',
    country: '英国',
    ranking: 50,
    website: 'https://www.bristol.ac.uk',
    description:
      '布里斯托大学是英国罗素集团成员，在工程、航空航天和地球科学领域实力强劲。位于英格兰西南部的布里斯托市，以工程和科研创新闻名。',
    requirements: { gpa_min: '3.2/4.0', toefl_min: 90, ielts_min: 6.5, gre: '建议308+' },
    tuition: '约£26,000/年（国际生）',
    application_deadline: '7月31日（多数项目）/ 滚动录取',
    logo_url: null,
  },

  // ====== 加拿大 (4) ======
  {
    name: '多伦多大学',
    name_en: 'University of Toronto',
    country: '加拿大',
    ranking: 19,
    website: 'https://www.utoronto.ca',
    description:
      '多伦多大学是加拿大排名最高的大学，在人工智能、医学和工程领域世界领先。位于加拿大最大城市多伦多市中心，多元文化氛围浓厚，是三一学院和维多利亚学院等著名学院的联合体。',
    requirements: { gpa_min: '3.4/4.0', toefl_min: 93, ielts_min: 7.0, gre: '建议315+' },
    tuition: '约CAD 55,000/年（国际生）',
    application_deadline: '12月15日（多数项目）',
    logo_url: null,
  },
  {
    name: '不列颠哥伦比亚大学',
    name_en: 'University of British Columbia',
    country: '加拿大',
    ranking: 36,
    website: 'https://www.ubc.ca',
    description:
      'UBC拥有温哥华和奥肯那根两大校区，在林业、海洋科学和计算机科学领域世界闻名。温哥华校区三面环海，被誉为北美最美校园，温哥华连续多年被评为全球最宜居城市。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 90, ielts_min: 6.5, gre: '建议310+' },
    tuition: '约CAD 50,000/年（国际生）',
    application_deadline: '12月1日（早申）/ 1月15日（常规）',
    logo_url: null,
  },
  {
    name: '麦吉尔大学',
    name_en: 'McGill University',
    country: '加拿大',
    ranking: 33,
    website: 'https://www.mcgill.ca',
    description:
      '麦吉尔大学素有"北方哈佛"之称，在医学、法学和生命科学领域国际声望极高。位于蒙特利尔市中心，是加拿大最国际化的大学之一，教学语言以英语为主。',
    requirements: { gpa_min: '3.5/4.0', toefl_min: 86, ielts_min: 6.5, gre: '建议315+' },
    tuition: '约CAD 48,000/年（国际生）',
    application_deadline: '1月15日（多数项目）',
    logo_url: null,
  },
  {
    name: '滑铁卢大学',
    name_en: 'University of Waterloo',
    country: '加拿大',
    ranking: 48,
    website: 'https://www.uwaterloo.ca',
    description:
      '滑铁卢大学以计算机科学、数学和工程学科闻名，拥有全球最大的带薪实习项目。位于加拿大科技三角区，毕业生深受硅谷和加拿大科技公司青睐。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 90, ielts_min: 6.5, gre: '建议312+' },
    tuition: '约CAD 45,000/年（国际生）',
    application_deadline: '2月1日（多数项目）',
    logo_url: null,
  },

  // ====== 澳大利亚 (3) ======
  {
    name: '墨尔本大学',
    name_en: 'University of Melbourne',
    country: '澳大利亚',
    ranking: 13,
    website: 'https://www.unimelb.edu.au',
    description:
      '墨尔本大学是澳大利亚排名最高的大学，在医学、法学、商学和生物科学领域位居世界前列。位于连续多年被评为全球最宜居城市之一的墨尔本，校园建筑融合古典与现代风格。',
    requirements: { gpa_min: '3.2/4.0', toefl_min: 79, ielts_min: 6.5, gre: '建议310+' },
    tuition: '约AUD 42,000/年（国际生）',
    application_deadline: '10月31日（第一学期）/ 4月30日（第二学期）',
    logo_url: null,
  },
  {
    name: '悉尼大学',
    name_en: 'University of Sydney',
    country: '澳大利亚',
    ranking: 16,
    website: 'https://www.sydney.edu.au',
    description:
      '悉尼大学是澳大利亚历史最悠久的大学，在医学、法学和艺术领域享有盛誉。主校区位于悉尼市中心，哥特式砂岩建筑被列为世界文化遗产，校园风景如画。',
    requirements: { gpa_min: '3.2/4.0', toefl_min: 85, ielts_min: 6.5, gre: '建议310+' },
    tuition: '约AUD 42,000/年（国际生）',
    application_deadline: '1月15日（第一学期）/ 6月25日（第二学期）',
    logo_url: null,
  },
  {
    name: '澳大利亚国立大学',
    name_en: 'Australian National University',
    country: '澳大利亚',
    ranking: 25,
    website: 'https://www.anu.edu.au',
    description:
      'ANU是唯一由澳大利亚联邦议会立法设立的大学，在政治学、国际关系、物理和地球科学领域研究实力顶尖。位于首都堪培拉，与政府机构和各国使馆联系紧密。',
    requirements: { gpa_min: '3.2/4.0', toefl_min: 80, ielts_min: 6.5, gre: '建议308+' },
    tuition: '约AUD 40,000/年（国际生）',
    application_deadline: '12月15日（第一学期）/ 5月15日（第二学期）',
    logo_url: null,
  },

  // ====== 新加坡 (2) ======
  {
    name: '新加坡国立大学',
    name_en: 'National University of Singapore',
    country: '新加坡',
    ranking: 8,
    website: 'https://www.nus.edu.sg',
    description:
      'NUS是亚洲排名最高的大学，在工程、计算机科学和商学领域全球领先。校园位于新加坡这座花园城市，融合东方和西方教育理念，毕业生就业率极高。',
    requirements: { gpa_min: '3.4/4.0', toefl_min: 92, ielts_min: 6.5, gre: '建议318+' },
    tuition: '约SGD 38,000/年（国际生）',
    application_deadline: '3月3日（8月入学）/ 8月26日（1月入学）',
    logo_url: null,
  },
  {
    name: '南洋理工大学',
    name_en: 'Nanyang Technological University',
    country: '新加坡',
    ranking: 17,
    website: 'https://www.ntu.edu.sg',
    description:
      'NTU以工程、材料科学和设计学科著称，校园被誉为全球最美校园之一。科研投入巨大，在人工智能和可持续发展领域建有世界级研究中心。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 90, ielts_min: 6.5, gre: '建议315+' },
    tuition: '约SGD 36,000/年（国际生）',
    application_deadline: '3月3日（8月入学）/ 8月26日（1月入学）',
    logo_url: null,
  },

  // ====== 香港 (3) ======
  {
    name: '香港大学',
    name_en: 'University of Hong Kong',
    country: '香港',
    ranking: 20,
    website: 'https://www.hku.hk',
    description:
      '港大是香港历史最悠久的大学，在医学、法学和牙科领域位居世界前列。位于香港岛薄扶林，中西文化交汇，是亚洲最具国际化的大学之一。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 80, ielts_min: 6.0, gre: '建议310+' },
    tuition: '约HKD 182,000/年（非本地生）',
    application_deadline: '12月31日（主轮）/ 滚动录取',
    logo_url: null,
  },
  {
    name: '香港科技大学',
    name_en: 'Hong Kong University of Science and Technology',
    country: '香港',
    ranking: 35,
    website: 'https://www.hkust.edu.hk',
    description:
      '港科大以工程、商学和计算机科学闻名，短短三十余年已跻身世界顶尖大学行列。位于清水湾，依山傍海，环境优美，是亚洲最年轻的顶尖研究型大学。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 80, ielts_min: 6.0, gre: '建议312+' },
    tuition: '约HKD 180,000/年（非本地生）',
    application_deadline: '12月15日（早轮）/ 滚动录取',
    logo_url: null,
  },
  {
    name: '香港中文大学',
    name_en: 'Chinese University of Hong Kong',
    country: '香港',
    ranking: 45,
    website: 'https://www.cuhk.edu.hk',
    description:
      '港中文是香港最大的大学，校园占地面积为全港之最，以商学、医学和翻译学科著称。位于沙田，背靠山峦面向吐露港，书院制教育独具特色。',
    requirements: { gpa_min: '3.2/4.0', toefl_min: 79, ielts_min: 6.0, gre: '建议308+' },
    tuition: '约HKD 170,000/年（非本地生）',
    application_deadline: '12月31日（主轮）/ 滚动录取',
    logo_url: null,
  },

  // ====== 欧洲大陆 (2) ======
  {
    name: '苏黎世联邦理工学院',
    name_en: 'ETH Zurich',
    country: '欧洲大陆',
    ranking: 7,
    website: 'https://www.ethz.ch',
    description:
      'ETH Zurich是欧洲大陆排名最高的大学，在工程、计算机科学和自然科学领域与MIT齐名。爱因斯坦母校，培养了众多诺贝尔奖得主，位于瑞士苏黎世，学术氛围浓厚。',
    requirements: { gpa_min: '3.5/4.0', toefl_min: 100, ielts_min: 7.0, gre: '建议320+' },
    tuition: '约CHF 1,460/年（极低学费）',
    application_deadline: '12月15日（多数硕士项目）',
    logo_url: null,
  },
  {
    name: '慕尼黑工业大学',
    name_en: 'Technical University of Munich',
    country: '欧洲大陆',
    ranking: 43,
    website: 'https://www.tum.de',
    description:
      'TUM是德国最顶尖的理工科大学，在工程、计算机科学和生命科学领域享有盛誉。与宝马、西门子等工业巨头紧密合作，毕业生在德国及欧洲就业优势巨大。',
    requirements: { gpa_min: '3.3/4.0', toefl_min: 88, ielts_min: 6.5, gre: '建议310+' },
    tuition: '约EUR 6,000/年（国际生）',
    application_deadline: '5月31日（冬季学期）/ 11月30日（夏季学期）',
    logo_url: null,
  },
];

/** Helper: get a school by array index, cast to full School type */
export function getSchoolById(id: string): School | undefined {
  const index = parseInt(id, 10);
  if (isNaN(index) || index < 0 || index >= seedSchools.length) return undefined;
  return { ...seedSchools[index], id: String(index), created_at: new Date().toISOString() };
}

/** Helper: get all schools with generated IDs */
export function getSchoolsWithIds(): School[] {
  return seedSchools.map((s, i) => ({
    ...s,
    id: String(i),
    created_at: new Date().toISOString(),
  }));
}
